### ISSUE TITLE
Allow proxies to be case insensitive

### ISSUE THREAD

**Issue by SimplyLinn** [xSke/PluralKit#103]
My friend has an issue where, on their phone, it keeps capitalizing the first letter automatically, so,
`a,text` becomes `A,text` while on the phone.

We've worked around this issue by duplicating each member and having one proxy with uppercase and one with lowercase, but it would be nice with a builtin feature to enable case insensitive proxies.

One way would be to enable regex proxies, which would also enable more complex proxies as a whole. For instance we use `text -fs` proxies, and with regex support we could use both `text -fs` and `text - fs`. But that's not as important to us specifically, just voicing this as an option.

There are security/performance concerns with [user specified regex though](https://www.regular-expressions.info/redos.html), but like that site suggests, [we could use a non-backtracking regex engine](https://github.com/google/re2/wiki/WhyRE2) to mitigate the security concerns.

If we don't go with the regex route, I'm thinking a system-wide setting for case-sensitivity, with member specific overrides, in case one member doesn't like it or something, or is the only one who wants it or something.

I'm willing to implement this myself and make a PR but since there's a discussion to be had about how to implement it, I'm creating an issue first.

**Comment by xSke** [comment]
I think the cleanest solution for this at the moment would just be adding support for multiple (traditional) proxies. An upgrade to that down the line could be regex proxies, but for now I'd rather focus on just multiple proxies.

**Comment by SimplyLinn** [comment]
That'd work, but I haven't looked to deep into the database structure and I'm not sure if I'm able to implement multiple proxies as my first attempt at a PR to this project, since, if my assumptions are correct, we'd have to migrate the old proxies to the new database structure that allows for multiple proxies per member.

That's a far step beyond just adding a case insensitive/regex flag somewhere and have the code react accordingly.

**Comment by xSke** [comment]
I'm already rewriting most of the code (see rewrite-cs branch), and I'll see if I can work this feature in there :) The issue with the case insensitive flag is that it's a significant code effort (not just the flag, but the related command infrastructure for setting/querying/showing/clearing it) for something that wouldn't cover particularly many use cases compared to a more generally applicable solution.
