### ISSUE TITLE
Add importing from another PluralKit Instance

### ISSUE THREAD

**Issue by BakaKiller** [xSke/PluralKit#108]
Hey there !

At the moment it is possible to export a system from the bot to a json file.
It is also possible to import a json file, but from TupperBox.
Would it be possible to import from a PluralKit export json file ?

Thanks for your future answers !

**Comment by PlatypodeCode** [comment]
I believe this is a planned feature in the rewrite and will not be added to the python version

**Comment by BakaKiller** [comment]
Oh ? I may have missed an information then !

**Comment by xSke** [comment]
This is implemented in the rewrite branch already :)

**Comment by BakaKiller** [comment]
Alright, so I've tried to start that new branch with the docker-compose you give but i get this error :
```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
```
Should I open another ticket ?

**Comment by xBelladonna** [comment]
> 
> 
> Alright, so I've tried to start that new branch with the docker-compose you give but i get this error :
> 
> ```
> Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
>    at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
>    at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
>    at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
> ```
> 
> Should I open another ticket ?

It sounds like your `pluralkit.conf` file is not set properly, from the traceback it looks like it's missing a key.

**Comment by BakaKiller** [comment]
Well, I don't know what I can do, I set up my pluralkit.conf like this :
```json
{
    "PluralKit": {
        "Bot": {
            "Token": "xxxxxxx(I won't show the token in public of course)xxxxxxxx"
        }
}
```
I mean, it's not that hard, so why would it not work ? ><

**Comment by BakaKiller** [comment]
... ok sorry my eyes suck. I missed a closing bracket. It seems to work now !
Thanks for your help ! :heart:
