### ISSUE TITLE
regression for frontpercent / "switch out" stats 

### ISSUE THREAD

**Issue by kuzetsa** [xSke/PluralKit#112]
This wasn't noticed during the beta, but there's a regression in "frontpercent"

Screenshot from prior to the regression:

![frontstats_PreRegression](https://i.imgur.com/BLH1uUN.png)

Some folks have use for the (no fronter) stat for various reasons.

**Comment by xSke** [comment]
Whoops, b6ba24d should have closed this one instead.

**Comment by clockworths** [comment]
Hello? Ive had pluralkit for a month now and all the sudden it's not working on any of my servers.

**Comment by theforesttech** [comment]
@clockworths not sure why you commented on this issue, but please join the support server and ask there in the future
