### ISSUE TITLE
Pluralkit won't work regardless of its permissions

### ISSUE THREAD

**Issue by clockworths** [xSke/PluralKit#129]
Hello. So I've had pluralkit for almost a month now and everything was working fine and dandy but all the sudden it stopped responding completely.

I checked permissions, I toggled with them and still no response from pluralkit. It's not working on any of my servers. I even tried creating a new account along with a different server on it and it still didn't respond. 

I also noticed that when I go to the website it shows that it's not authorized or something and I want to know how to fix that.

**Comment by funnybone800** [comment]
This is happening to me as well. Out of no where too, I even tried readding it to my chat but it didn't work at all. Hope this gets fixed soon. Here's an example of it not working.
![image](https://user-images.githubusercontent.com/49191426/65828808-bc403c00-e253-11e9-8357-a2b435d4829b.png)

**Comment by PlatypodeCode** [comment]
This is likely because discords api has been acting up and breaking a lot of things.
Which website are you referring to? The command website is the only one run by pluralkit and it seems to be functioning well.

**Comment by PlatypodeCode** [comment]
To clarify: Pluralkit may need to be restarted to fix some of the problems, however many bots have been having issues for the past few months as discords api hasn't been functioning very well.

**Comment by xSke** [comment]
The server ran out of disk space :) It's fixed now.
