### ISSUE TITLE
Add an explicit character limit to system/member descriptions

### ISSUE THREAD

**Issue by xSke** [xSke/PluralKit#14]
Embeds break past 1024 characters per field, so if you try to set a description past that (up to 2000, which is the command message limit), it'll silently break posting the card.

**Comment by Ryonez** [comment]
A paginator could potentially help, maybe something like this:
```python
def pagify(text, delims=["\n"], *, escape=True, shorten_by=8,
           page_length=2000):
    """DOES NOT RESPECT MARKDOWN BOXES OR INLINE CODE"""
    in_text = text
    if escape:
        num_mentions = text.count("@here") + text.count("@everyone")
        shorten_by += num_mentions
    page_length -= shorten_by
    while len(in_text) > page_length:
        closest_delim = max([in_text.rfind(d, 0, page_length)
                             for d in delims])
        closest_delim = closest_delim if closest_delim != -1 else page_length
        if escape:
            to_send = escape_mass_mentions(in_text[:closest_delim])
        else:
            to_send = in_text[:closest_delim]
        yield to_send
        in_text = in_text[closest_delim:]

    if escape:
        yield escape_mass_mentions(in_text)
    else:
        yield in_text
```
A little something found from Red: https://github.com/Cog-Creators/Red-DiscordBot/blob/develop/cogs/utils/chat_formatting.py

Note, there's a limit of 20 fields to an embed and while the field character limit is 1024, the descriptions limit is 2048.

**Comment by xSke** [comment]
I'd rather cap it than deal with complex pagination stuff, honestly. 1024 should be enough.
