### ISSUE TITLE
RFC: Autoproxy

### ISSUE THREAD

**Issue by xSke** [xSke/PluralKit#149]
# RFC: Autoproxy
This proposes adding a feature that lets messages without proxy tags be recognized and proxied as a certain member, depending on the configuration.

## Background
It's been suggested a lot, I guess.

## Usage
Autoproxy can be enabled on a per-system and per-server basis. There will be several modes of autoproxy:

### Front mode
"Front mode" will proxy any message without proxy tags as the current listed fronter, using the first if multiple are listed. Proposed command syntax:

    pk;autoproxy front 

This will enable front-mode autoproxying for the current server.

### Latch/last mode
"Latch mode" will autoproxy using the last member that explicitly proxied. In this mode, if member A proxies using their tags, future messages without proxy tags will be proxied as A.
If a member B then proxies using *their* proxy tags, future messages will be proxied as B, and so on. Proposed command syntax:

    pk;autoproxy latch

This will enable latch-mode autoproxying for the current server.

### Member mode
This will autoproxy using a specific defined member. Proposed command syntax:

    pk;autoproxy <member name or ID>

## Potential issues
- There's no way to "opt out" per-message of autoproxying, which could be useful for, say, using commands on other bots. Perhaps either a preset or configurable "escape character" (such as a backslash) could work to negate autoproxying.
- More frequent proxying could potentially put additional load on the bot and the Discord API.
- Setting autoproxy "per-server" could lead to users forgetting having enabled autoproxy when talking somewhere they haven't in a while, and potentially leaking unwanted information.
- More autoproxy modes may be needed or be useful. I can't think of any at the moment but suggestions appreciated.

**Comment by PlatypodeCode** [comment]
Due to the way the discord api works, other bots will not be prevented from reading the original message before autoproxy. However some errors in other bots could happen from the original message being deleted. But if other bots are coded to good standards then it shouldn't be an issue (aka it's more of a them problem).
I don't believe proxing would be increased by much if at all, because most people asking for autoproxy aren't just not proxing, they are just using the normal proxy method.
I am not sure what to do about the potential privacy leak. I think a vote on global vs per sever would be best

**Comment by xSke** [comment]
@PlatypodeCode I'm definitely leaning towards per-server autoproxy. I can absolutely see situations where you'd want it enabled in one place and not others. The "forgetting" issue seems relatively minor to me, but I wanted to bring it up anyway in case someone considers it more important.

**Comment by silasary** [comment]
For multi-account systems, would this be set per-account or per-system?

**Comment by xSke** [comment]
> For multi-account systems, would this be set per-account or per-system?

With the current implementation (#150) it's per-system.
