### ISSUE TITLE
Blocking pluralkit system members? 

### ISSUE THREAD

**Issue by smouldery** [xSke/PluralKit#159]
For channel messages from individual members of a system, what is the process to block / no longer see these at a user level?

I tested blocking the whole bot, even that didn't work - is there something I'm missing or is it just impossible to block pluralkit users?

**Comment by 0xlgs** [comment]
Unfortunately, it's impossible to block individual members (or even everyone who sends messages through PluralKit). Messages are sent through webhooks, which just have an option to specify the username and avatar at each message sending - so there is no user that exists to block.

**Comment by smouldery** [comment]
No worries, thank you for confirming this :)
