### ISSUE TITLE
Add the ability to accept names with spaces in commands. 

### ISSUE THREAD

**Issue by Ryonez** [xSke/PluralKit#16]
At the moment, commands use spaces as markers for the next segment of a command. If you use both a given name and a forename, a command will not take it in as a whole name. Even when using quotes, it will try to split it.

While there is an alternative method, using id's, it's more likely a member will remember the name at all times.

Could you please modify commands that use member names to be able to take names with spaces in quotes as well?
And while I have a system name that's just a single word, it would probably be if benefit from the same addition to the commands feature set.

Cheers.

**Comment by xSke** [comment]
It does rudimentary quote parsing in the `next_arg` function in
`commands/__init__.py`, although that only supports double quotes. Is that
broken?

**Comment by Ryonez** [comment]
It seems... I'm a derp. 
When I was setting up the name of one of my members it seems I started spelling the name incorrectly after setting it. A little strange, I completely missed it at the time. Sorry, for the incorrect submission, it does indeed seem to work perfactly fine.
