### ISSUE TITLE
Add an option for "Latch" autoproxy mode to remember last proxy per-user

### ISSUE THREAD

**Issue by HerrahStrings** [xSke/PluralKit#162]
Mode could be named `user-latch` or similar. Autoproxies a message based on the last proxy used by the user sending said message.

**Example Use Cases**
- Plural multitasking - One system, using a phone and a desktop logged in on different users, holding two different conversations at once.
- Roleplaying Tool - Two seperate users who (as a workaround) share a system, could roleplay as the same member at times, but one changing proxy wouldn't affect the other.

**Comment by xSke** [comment]
This is already how autoproxy works (as that was more efficient on the database). Gonna close this for now, feel free to re-open if I'm reading this wrong.
