### ISSUE TITLE
Systems activating when @ing a member of the server

### ISSUE THREAD

**Issue by AeternumWarrior** [xSke/PluralKit#165]
Whenever I (or any other member of my server) attempts to @ another member, 
Their system activates without the proxy, and gives a weird code?
![Screenshot_20200424-172401_Discord](https://user-images.githubusercontent.com/64291540/80266390-7b28d280-8650-11ea-985f-4f2e403b74bc.jpg)

**Comment by xSke** [comment]
Does it only happen when mentioning that specific member? Does it only happen when certain members *do* it? Do you have a system registered with autoproxy enabled?

**Comment by AeternumWarrior** [comment]
It happens when any member of the server tries to @ anyone. 
And Autoproxy is disabled in the server.

**Comment by xSke** [comment]
That very much shouldn't happen, I'm not sure what could be causing that. If you remove PluralKit's permissions in a channel, does it still happen? What if you kick it entirely?

**Comment by AeternumWarrior** [comment]
If pluralkit's perms are removed, it no longer activates the systems, and I haven't tried kicking pluralkit and reinviting it yet

**Comment by xSke** [comment]
One thing that could cause it is if you have a member set up with `<text>` proxy tags. Discord represents pings as `<@userid>` in text form, so PK will pick up on those brackets and treat them as a proxy. It's generally recommended to not use those proxy tags for that reason. However, this may not be it if it happens for *every* member of the server. Does it still happen if a server member who *doesn't* have a PluralKit system registered pings someone?

**Comment by AeternumWarrior** [comment]
Ah! It was the <text> proxy!
Apparently all of us had a proxy that included <text>
Thank you so much for your help!
