### ISSUE TITLE
Add option to show current fronter(s) as a custom status 

### ISSUE THREAD

**Issue by PrimalSystemStudio** [xSke/PluralKit#187]
Proposed syntax: `pk;activity` or `pk;activity on`
Bot would respond:
`This will display the current fronters as a custom status and would be visible on your Discord profile. Proceed?` 
And it would display a tick and a cross similar to when you do `pk;switch move`.

I made an attempt to do this myself via an external bot but I'm not familiar with working with OAuth or C# so it's been a bit difficult. Just a suggestion and I think it would be quite helpful for people who are out to people on Discord.

**Comment by silasary** [comment]
This would require people to be running software on their local machine, as bots cannot change the status of other users.

**Comment by BeeFox-sys** [comment]
this is not something pluralkit itself can achieve; see https://github.com/BeeFox-sys/PluralkitRPC/releases/tag/2.0.0 for my attempt at a program that would do the same

**Comment by PrimalSystemStudio** [comment]
Thank you, I didn't know that.
