### ISSUE TITLE
[BUG] Messages with a newline after the beginning proxy tag doesn't get proxied

### ISSUE THREAD

**Issue by ent3r** [xSke/PluralKit#188]
Let's say a user tries to quote a message. They then add the proxy tag (in this case `{`) to the start, so the message becomes

```
{
> Ohh yeah, quote time
@ent3r oh yeah, love quotes
```

This message would then be sent, but pluralkit wouldn't proxy it.

If we then change the message to be

```
{Some content after the proxy tag
> Ohh yeah, quote time
@ent3r oh yeah, love quotes
```

the message gets proxied just fine.

-----

So essentially, the issue is that PluralKit doesn't proxy messages without a character after the proxy tag, even if that character is on a new line.

**Comment by acw0** [comment]
This seems to work for me:

![Image](https://img.spiral.li/uaz8cndq92.gif)

**Comment by acw0** [comment]
Does your proxy tag have a space between `{` and `text`? I've seen that create issues at times.

**Comment by ent3r** [comment]
Yeah, that's when you add a character after the proxy tag. If you try without it, it shouldnt work
In your case,
```
-
test
```
wouldnt work

**Comment by xSke** [comment]
Could have it collapse a leading/trailing space into "any whitespace", which would match newlines as well?

**Comment by acw0** [comment]
My proxy tags are `~/text`, so that wouldn't work, but not for the reason you mentioned.

**Comment by ent3r** [comment]
Oh, I thought your proxy was `~text`. Seems this issue isn't that reproducible. That's weird

**Comment by ent3r** [comment]
I'll close this since I can't manage to reproduce it anymore. May have been a one-off glitch or something
