### ISSUE TITLE
Tupperbox imports fail

### ISSUE THREAD

**Issue by dev-kittens** [xSke/PluralKit#220]
A recent change to Tupperbox's export system means that it now exports tupper IDs and possibly other fields that were not previously included in an import file.
As Newtonsoft.Json appears to not ignore unknown fields, this means all imports now fail.

Here's an example error: `Newtonsoft.Json.JsonSerializationException: Could not find member 'id' on object of type 'TupperboxTupper'. Path 'tuppers[0].id', line 1, position 18.`

While this could be fixed on Tupperbox's side by not exporting unnecessary fields (or on ours by adding the new fields to the import struct), I think it would be better to fix this issue by ignoring unknown fields while parsing JSON, as it would also make this future-proof for any new export file additions.

**Comment by xSke** [comment]
Fixed by https://github.com/xSke/PluralKit/commit/509c0bf73f0b1dcb4f127d8ef0402eeb658723d5
