### ISSUE TITLE
bot dming other people about my profile

### ISSUE THREAD

**Issue by LegendaryGeek** [xSke/PluralKit#222]
in a server i admin a member started recieving rogue dm's from the bot about things that shouuld have only been available in the server. upon further inspection, it appears moderation tools were enabled. but given a user a message about a message i sent when it shouldnt have. 
![image](https://user-images.githubusercontent.com/45850917/94635159-ff3a5280-029f-11eb-879f-c9b7428acf23.png)

**Comment by dev-kittens** [comment]
This happens when anyone reacts to a proxied message with a question mark (❓ ) emoji.
