### ISSUE TITLE
Appears not to support python 3.8?

### ISSUE THREAD

**Issue by fw4hre0xxq** [xSke/PluralKit#239]
I tried following the docker instructions on a fresh Ubuntu 20.04, and it failed to build. Googling the error led me to the conclusion that python 3.8 isn't supported. Is this the case?

**Comment by dev-kittens** [comment]
PluralKit hasn't used Python in a really long time. What's the error, so we could help properly figure out what's wrong?

**Comment by xSke** [comment]
Yes, the `legacy` branch (which hasn't been actively used since mid-2019) is Python 3.6 only, IIRC. But... you probably shouldn't use it :) Use the `main` branch instead, on .NET Core 3.1.

(if there's a different issue, feel free to re-open this)
