### ISSUE TITLE
PluralKit Can Be Used to Evade Blocks

### ISSUE THREAD

**Issue by sombraTheOracle** [xSke/PluralKit#240]
In a server one of my friends is in, they have a person's main account blocked, but that person is still able to @ them while using a member proxy. In addition, I've noticed some undefined behavior with system members on the Android Discord mobile app, where sometimes the system members show up with a partial profile that you can't interact with, and other times the requests hang. Not sure how much of a problem this is, but it's very strange.

**Comment by silasary** [comment]
This is the nature of Discord webhooks, on top of which PluralKit is built.  There's no way to change this behavior.

See https://pluralkit.me/faq/#is-it-possible-to-block-proxied-messages-like-blocking-a-user

**Comment by xSke** [comment]
Yeah - this is a Discord limitation and there's no way for the bot to fix this, unfortunately. It does suck, though, and we're very aware of it.

And, the partial profile thing is also a Discord client bug with webhooks.
