### ISSUE TITLE
Support reply function

### ISSUE THREAD

**Issue by EvyBongers** [xSke/PluralKit#259]
With the new reply function that Discord is rolling out, messages can be replied to without quoting the content and instead linking back to the message that's being replied to.

When a message is proxied, currently the replied-to message isn't picked up and the reply function looses it's usefulness.

Please update the bot to pick up on the message being replied to, and have the message created by the bot take over the reply to.
Note: reply function optionally mentions the user who posted the original message. Please take this into account when posting the message via webhook.

**Comment by dev-kittens** [comment]
Duplicate of #256

**Comment by EvyBongers** [comment]
When I have more time (hopefully soon), I'm willing to have a go at it. I should warn that it's been ages that I used .NET, so I'm not sure how long it would take me to implement it.

**Comment by EvyBongers** [comment]
Sorry, looked but missed #256. Closing this one.
