### ISSUE TITLE
Disabling front/latch autoproxy on a per-member basis not recognized

### ISSUE THREAD

**Issue by Ash-Forest** [xSke/PluralKit#263]
As seen here in the documentation [https://pluralkit.me/guide/#autoproxy](https://pluralkit.me/guide/#autoproxy) the command "pk;member <name> autoproxy off" is not recognized by the bot. 

![image](https://user-images.githubusercontent.com/10049622/101802785-be648280-3b07-11eb-85e6-3c6629804bfb.png)

**Comment by xSke** [comment]
This was implemented in #252, which was merged two days ago but hasn't been deployed to the live bot until just now. It should work now :)
