### ISSUE TITLE
Hows do you access the API?

### ISSUE THREAD

**Issue by Ryonez** [xSke/PluralKit#31]
Is there any kind of quick guide for this please?

**Comment by xSke** [comment]
The API is unfinished and undocumented but you can check the source for the endpoints: https://github.com/xSke/PluralKit/blob/master/src/api_main.py#L107.

The root is "pkapi.astrid.fun", until I buy a domain for it.

**Comment by Ryonez** [comment]
I've tried looking at it, but I lack the knowledge to decipher it properly.
What is being asked for by the {id} value? The user/system unique id's?

While that would get some specific info, I was looking at trying to get some general info, like the total number of systems/members, total messages sent, that kind of thing. I vaguely remember you saying you display something like that on a grafana dashboard, though I may be mistaken.

**Comment by xSke** [comment]
The {id} is the 5-character code for the system/member. There's no overall stats for the bot yet. You're right, I had that on a Grafana dashboard but I took that down for (lack of) maintenance reasons.

**Comment by Ryonez** [comment]
I see. Any chance they'll be restored?

**Comment by xSke** [comment]
Probably not the dashboard, but I can add endpoints for it When I Have Time™.

**Comment by Ryonez** [comment]
Alright, thank you for the answers.
