### ISSUE TITLE
PK suddenly stopped working in one of my servers?

### ISSUE THREAD

**Issue by BambiIsHere** [xSke/PluralKit#319]
Been using PK for about a month and suddenly it stopped working in only one of my servers?
I have it in 3 servers total and I have removed and re-added the bot twice but it is still not working.

**Comment by xSke** [comment]
It's been a known issue for a few hours. Seems to be a problem on Discord's end, happening to a few specific servers with no clear pattern in which (it's not shard-specific). Tupperbox is having the same issue at the moment, so all we can really do is wait.
