### ISSUE TITLE
Fix message card

### ISSUE THREAD

**Issue by IbisLiven** [xSke/PluralKit#32]
the message card always has "(unknown, message deleted)" set as the message contents.

there is likely a problem with this function or the data being passed to it in line 57
https://github.com/xSke/PluralKit/blob/10746ae807bb5db7f6de57927bd4974efa3d074c/src/pluralkit/bot/commands/message_commands.py#L7

**Comment by xSke** [comment]
This is a regression from the discord.py rewrite branch. The str() call breaks the internal channel lookup since the new code uses ints for IDs. I'll fix this once I get access to a computer, unless you want to do a PR?
