### ISSUE TITLE
Fix Discord lumping together hooks by the same name

### ISSUE THREAD

**Issue by xSke** [xSke/PluralKit#33]

**Comment by xSke** [comment]
Currently unsure how to effectively solve this. I know adding a space "breaks" the grouping but I'm not sure what state to keep to do this properly. "if a proxy has the same name as the last message proxied in the same channel but different member id" doesn't work because that a) breaks once, then unbreaks, which will break the group twice, and b) not work if you're interrupted by an unproxied message.

**Comment by inexactually** [comment]
I think the stateful idea you had is almost there? You keep track of the name and userid of the last proxied message, as well as whether or not you added a space. Then when the new proxied message has the same name:
- if it's by the same user, add the same suffix as before (space or nothing)
- if it's by a different user, add the opposite suffix (nothing or space) 
If you're interrupted by an unproxied message this might add a space when it doesn't need to, but that doesn't cause any problems. If the same person proxies the same name several times in a row, it'll either add the space to all of the messages or none of them.

**Comment by xSke** [comment]
Yeah, that makes sense. That'd require me to refactor proxy.py into actually holding state somewhere rather than just being a few free functions, and that's something I'm kind of reluctant to do, but I'll work it out :)

**Comment by acw0** [comment]
Tupperbox does this by adding a `\u200a` character between the first and second character of the webhook username.
This is now simpler to implement because of the [LastMessageCache](https://github.com/xSke/PluralKit/blob/main/PluralKit.Bot/Services/LastMessageCacheService.cs). Maybe worth looking into, not sure if this is still an issue?

**Comment by spiralw** [comment]
Closed in 25f96dd920b9a1de187fc04640581f16245289b6.
