### ISSUE TITLE
[Request for maintainer feedback] Exceptions used unnecessarily

### ISSUE THREAD

**Issue by BeautifulPixel** [xSke/PluralKit#330]
```C#
public static Guild MatchGuild(this Context ctx)
    {
        try
        {
            var id = ulong.Parse(ctx.PeekArgument());
            ctx.Cache.TryGetGuild(id, out var guild);
            if (guild != null)
                ctx.PopArgument();

            return guild;
        }
        catch (FormatException)
        {
            return null;
        }
    }
```

This code comes from `ContextEntityArgumentsExt.cs`. It uses an exception as part of normal control flow, which makes the code harder to read and is pretty bad for performance (exceptions are extremely nonperformant). While exceptions definitely have their use cases, this one would be pretty easy to refactor out, and I'm sure there are others like it. I wanted to ask whether you'd like to see them fixed. If you'd prefer to leave it the way it is (which would be valid!), then there's no point in me going haring off trying to fix it. :)

**Comment by spiralw** [comment]
bit late, but thanks for catching this. we do use exceptions (`PKError`s) for control flow, but this specific case does seem wrong. please do send a PR!
