### ISSUE TITLE
Bot is down? 

### ISSUE THREAD

**Issue by DoomStrider** [xSke/PluralKit#334]
Hi, plural kit is down on my discord server where we use it extensively, is this a global issue or just me?

**Comment by tarltarasa** [comment]
It's a global issue right now. The bot is down and Astrid (who runs it) isn't online to turn it back on.

**Comment by spiralw** [comment]
This is a global issue, yes. ^^
In the future, please join the support server at <https://discord.gg/PczBt78> to report downtime - this repo is more of for bugs and feature requests.
