### ISSUE TITLE
Newbie to PluralKit

### ISSUE THREAD

**Issue by RenFlow** [xSke/PluralKit#347]
Is there any documentation about what this does and/or why I would want to install it? What problem does PluralKit solve? I read the "documentation" on the home page of https://pluralkit.me/ , but this makes zero sense to me.

**Comment by ChildishGiant** [comment]
It's a tool for [plural](https://pluralityresource.org/plurality-information/) folks. Most people don't need to use it

**Comment by spiralw** [comment]
From the `pk;explain` command:

> > **About PluralKit**
> PluralKit detects messages enclosed in specific tags associated with a profile, then replaces that message under a "pseudo-account" of that profile using Discord webhooks.
>
> This is useful for multiple people sharing one body (aka. *systems*), people who wish to role-play as different characters without having multiple Discord accounts, or anyone else who may want to post messages under a different identity from the same Discord account.
>
> Due to Discord limitations, these messages will show up with the `[BOT]` tag - however, they are not bots.
