### ISSUE TITLE
Bot down in only one server

### ISSUE THREAD

**Issue by PXellion** [xSke/PluralKit#351]
I'm in four servers which include the pluralkit bot, and it appears as Online in three of them. The fourth, my server, it is appearing Offline. I tried removing the bot and re-adding it but that did not change anything. It also does not respond to any of my commands including the pk;help command

I've read through the Pluralkit site and couldn't find anything suggesting how to fix this issue, and I scrolled through threads here on Github to see if there were any that describe the same problem but did not see one. If this question has already been answered, please let me know

Thank you!

**Comment by spiralw** [comment]
Please join the support server to report downtime: https://discord.gg/PczBt78
