### ISSUE TITLE
Additional FAQ entry

### ISSUE THREAD

**Issue by rladenson** [xSke/PluralKit#355]
My file isn't importing properly troubleshoot list: 
-Do you have any proxy tags longer than 100 characters? 
-Do you have any switches with more than 100 members?
-Did you ever import from Simply Plural? If yes or unsure, check that each member's colors are valid hex codes. (Valid hex codes are six characters with each character being either a digit from 0-9 or a letter from a-f eg "ab03ff")

**Comment by xSke** [comment]
Would rather just fix the underlying issue instead of adding a FAQ entry to deal with our bugs :)

**Comment by rladenson** [comment]
Okie! Makes sense :)

**Comment by spiralw** [comment]
re: the colors issue - would it just be better to import the file without the colors instead of hard crashing?
