### ISSUE TITLE
Code formatting is broken on Android

### ISSUE THREAD

**Issue by mdpkh** [xSke/PluralKit#369]
In responses to pk;system list, PluralKit encloses the proxy strings for each member in double backticks, which either isn't a correct formatting code in Discord, or it's supposed to be but it doesn't work in the Android client. Single backticks are the correct formatting for inline code quoting; maybe then further enclose the backtick-enclosed string in quotation marks, if such marks should be visible in the output.

**Comment by spiralw** [comment]
Single backticks are not the correct formatting for inline code quoting. There is no way to escape a backtick inside a single-backtick quote - that is why we use double backticks. This is a Discord Android bug, and it's on Discord to fix it. Sorry :/

I will look into what we can do about this in the meantime, but the answer is probably going to be "nothing", unfortunately :(

**Comment by spiralw** [comment]
It is now not broken anymore, as of https://github.com/discord/SimpleAST/pull/35 :tada:
