### ISSUE TITLE
Autoproxy should show all fronter in tag

### ISSUE THREAD

**Issue by bskrtich** [xSke/PluralKit#408]
Since we can set multiple members as fronting using the pk;switch command, it would be great if autoproxy fronter would use all the names that are fronting at the current time.

**Comment by rladenson** [comment]
There are both practical issues with this (what if the names of all fronters exceeds the discord webhook name character limitation?) and many people would not actually want this as they put everyone coconscious in the switch, not just everyone actively fronting. You can make a utility member that you change the displayname of for this purpose if you'd like, though!

**Comment by bskrtich** [comment]
I figured as much but if this was put behind a setting and just trim the name length if it exceeds the discord length it should be easy enough to add.

**Comment by spiralw** [comment]
this is not really something I'm interested in implementing, sorry
