### ISSUE TITLE
hex codes and member working

### ISSUE THREAD

**Issue by ChetariSin** [xSke/PluralKit#41]
so i added two tulpas to Pluralkit. only one of them, Pluralkit doesn't acknowledge. i keep trying to do stuff with it but it keeps saying that the tulpa doesn't exist. and the Coloring. i tried hex codes and it keeps saying that the hex codes aren't valid. even when i tried the hex code it used as an example. you people really need to make it more manageable to use.

**Comment by xSke** [comment]
Could you give me some more information on specifically what your issue is? Just complaining "it doesn't work" doesn't give me much to go off of.
