### ISSUE TITLE
Actual discord replies

### ISSUE THREAD

**Issue by krsnik02** [xSke/PluralKit#442]
Can we make proxied messages to use discord's inbuilt replies instead of an embed like it currently does or is there some technical reason this isn't currently possible?

**Comment by xSke** [comment]
Webhooks can't use replies on Discord's end.

**Comment by rladenson** [comment]
Discord doesn't let webhooks access that feature :/

**Comment by krsnik02** [comment]
thought it was probably something like that. sad
