### ISSUE TITLE
Add / slash command support?

### ISSUE THREAD

**Issue by pigsflew** [xSke/PluralKit#443]
Would it be possible to add support for proxying via slash command? I believe that would allow the message to be proxied to never appear, rather than appearing and then being "removed" and replaced.

**Comment by spiralw** [comment]
unfortunately, slash commands MUST reply with a message, so the user who is sending the original message will still see a message - that the bot then cannot delete, so the user has to delete it themself.

I really hope Discord improves here, but they don't really seem to be interested in doing so :(

**Comment by xSke** [comment]
I know the slash command *used* to have that feature in the early API versions but it then disappeared for some reason. Maybe if we bug 'em enough they'll add it back...
