### ISSUE TITLE
database_uri in `docker-compose.yml` overrides the one in pluralkit.conf 

### ISSUE THREAD

**Issue by Ryonez** [xSke/PluralKit#56]
As stated on the tin.

May be related to #55

**Comment by xSke** [comment]
Intended behaviour, the docker-compose file also describes the database container and the way it connects to the main bot. This mirrors the behaviour from before the change.

**Comment by Ryonez** [comment]
Rodger that, I'll just stick to editing the docker compost file for now then.

**Comment by xBelladonna** [comment]
Wait... so what is the point of specifying the database URI in the config file?

**Comment by xSke** [comment]
None if you're using the docker-compose file :)

**Comment by xBelladonna** [comment]
Ah, understood.
