### ISSUE TITLE
Custom bot prefix per-server

### ISSUE THREAD

**Issue by greysdawn** [xSke/PluralKit#65]
custom stuff for servers

examples:
- `pk;prefix kek;` changes commands to `kek;command`
- `pk;blacklist #channel` adds channel to proxying blacklist (easier for mobile server owners who struggle w/ bot permissions and just give pk admin)

**Comment by xSke** [comment]
re: the prefix - sure, I could add that.
re: the blacklist - I feel like a blacklist should be accompanied by a whitelist. What should the UX be for picking whether you want a blacklist or a whitelist? To me, having both does not make sense, should be either/or. What do you think?

**Comment by greysdawn** [comment]
maybe you could have `pk;whitelist` and `pk;blacklist` commands, with add/remove subcommands, where they'd warn you about switching to the other type

example:
`pk;blacklist add #channel-name`
PK: Blacklist updated!
`pk;whitelist add #channel-name`
PK: WARNING: this will overwrite your current blacklist configuration to be used as a whitelist instead. React with ✅ to confirm you want to do this.

and then each command could have a `list` feature that would tell you if you're using the blacklist or whitelist and then which channels are included when you use the "right" one

eg:
`pk;whitelist` (or `pk;whitelist list`)
PK: You are not using a whitelist in this server. Did you mean `pk;blacklist`?
`pk;blacklist`
PK: Currently blacklisted channels: [insert embed or list]

i can try to draft up some more ideas if you'd like, but i hope that helps for now

**Comment by xSke** [comment]
Status update: Proxy blacklist has been added (long time ago!), custom prefix still unimplemented - may happen at some point.

**Comment by spiralw** [comment]
we've not really gotten any feature requests for a custom prefix. it's possible to choose your own prefix if you self-host the bot, and that seems good enough... if someone actually does want custom prefixes in the bot, let us know and we can re-open this issue :smile:
