### ISSUE TITLE
Add pronouns to the message sent when a :question: react is added

### ISSUE THREAD

**Issue by valknight** [xSke/PluralKit#73]
**Current Issue**

We're running into an issue on the server AGS wherein it's hard to get pronouns for a member, with the expected UX flow being to add :question:, and then you should be told this relevant information, however pronouns are then not sent when this reaction is made.

**Attempts to fix**

Currently, the solution members are using is to rename themselves to contain their pronouns in the user handle, however this is an ugly solution right now, as it means those who go by multiple pronouns may not be able to fit all of their pronouns into the character limit.

**Proposed solution**

Adding the pronouns into the message :question: sends back would solve this issue for us.

**Comment by xSke** [comment]
Would a solution like this be appropriate? 
![image](https://user-images.githubusercontent.com/16242158/56098542-9fac8380-5f01-11e9-87c9-999e9a8f7d8e.png)

**Comment by xSke** [comment]
Pushed that ^^ If you need something different, just reopen and comment :)

**Comment by valknight** [comment]
that's perfect, thank you so much!
