### ISSUE TITLE
Hidden members proposal

### ISSUE THREAD

**Issue by xSke** [xSke/PluralKit#89]
This will allow you to hide a member from your system list. For example for syskids, RP characters, or other members you may not want publicly visible.

* Hidden members should not appear in `pk;system list` or `pk;system list full`
  * Except if someone requests their own system list, in DMs
  * Otherwise, it should display a note explaining this in the list footer.
  * TODO: should there be a command variation to publicly show hidden members?
* Members can be hidden using a `pk;member <member> hide` command.
  * TODO: should this be a single toggle command or a `hide/unhide` pair?
* Hidden members can still be queried with their member ID and name (name only if it's the owner's system, as is already the case)
* Hidden members are still proxyable, and information about them will show if a message is queried.
* Hidden members will only show in the API member list if you're authenticated with token and are querying your own system

**Comment by PlatypodeCode** [comment]
Hidden members should not be able to be queried with the member command unless in DMs, and/or their Member ID should not be shown in the message query response

**Comment by xSke** [comment]
@PlatypodeCode You already can't query anyone with their member name unless you're doing the querying on your own system. I don't intend this feature to be for members that absolutely have to be kept secret at all costs (you should avoid proxying them, or use a different account, or not log them at all), but for members that you just wouldn't want showing up in a list with everyone else.

**Comment by xSke** [comment]
Closed in favor of member privacy, implemented in 98613c42870cef49059fb9fba3033358fcb78787.
