### ISSUE TITLE
System name has no length protection

### ISSUE THREAD

**Issue by PlatypodeCode** [xSke/PluralKit#92]
The length on the system name is not checked to have a maximum length, like the system description does.
This could potentially result in someone exceeding the character limit when querying a system with an extremely long name.
(Despite the fact no name should be that long, I do recommend a max length of 100 characters)

**Comment by xSke** [comment]
This is fixed in the rewrite branch, so I'll just leave this here and close it when it gets merged. https://github.com/xSke/PluralKit/blob/rewrite-cs/PluralKit/Bot/Limits.cs#L3
