### ISSUE TITLE
Multiple language support

### ISSUE THREAD

**Issue by BakaKiller** [xSke/PluralKit#98]
Hey !
Maybe the bot config could support new languages !
With jsoned strings (in a .en.json file for english, .fr.json for french etc) which would default to english.
That way we could more easily translate help and messages for non english discord servers !
I would gladly add a french translation if it is possible :)

**Comment by PlatypodeCode** [comment]
I support this and also suggest in the rewrite that it can be a server setting, so that servers do not have to self host the bot. Possibly a folder which contains json files so that it can be easily added to without having to rewrite part of the bot to find the new language

**Comment by BakaKiller** [comment]
That might be a bit harder but may be interresting yes !
A command like `pk;language` would give current language, `pk;language list` the list of available languages, `pk;language add [customlang] [linktojson]` would add a custom language stored in db or physically on the server and `pk;language set [lang]` would set bot language for the server ?

**Comment by xSke** [comment]
This will likely not be implemented, sorry. Lack of resources.
